version: '3.3'

services:

  nodejs:
    container_name: nodejs
    build: .
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - dvapi-mongodb

  dvapi-mongodb:
    container_name: dvapi-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - dvapi-mongodb-data:/data/db

volumes:
  dvapi-mongodb-data:
